axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 1.2
scale_angular_turbo: 1.8

enable_button: 0  # A button
enable_turbo_button: 1  # B button
